// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeWa5FGWeIIXzJbcea9ekOkxEGGg-lBzo',
    appId: '1:823070757258:web:e2d69182019dc149db3873',
    messagingSenderId: '823070757258',
    projectId: 'test1-cc8b6',
    authDomain: 'test1-cc8b6.firebaseapp.com',
    storageBucket: 'test1-cc8b6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQtz4HrxVNe5LjUw3tDI2cgF_vOcIpbt4',
    appId: '1:823070757258:android:70b7eb3fd7332b9adb3873',
    messagingSenderId: '823070757258',
    projectId: 'test1-cc8b6',
    storageBucket: 'test1-cc8b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCJBBaoS_BczdmqZgE0DhOq2NVVbOfxGo',
    appId: '1:823070757258:ios:b401f1a41ff4b508db3873',
    messagingSenderId: '823070757258',
    projectId: 'test1-cc8b6',
    storageBucket: 'test1-cc8b6.appspot.com',
    iosBundleId: 'com.example.test918',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCJBBaoS_BczdmqZgE0DhOq2NVVbOfxGo',
    appId: '1:823070757258:ios:b401f1a41ff4b508db3873',
    messagingSenderId: '823070757258',
    projectId: 'test1-cc8b6',
    storageBucket: 'test1-cc8b6.appspot.com',
    iosBundleId: 'com.example.test918',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeWa5FGWeIIXzJbcea9ekOkxEGGg-lBzo',
    appId: '1:823070757258:web:0f716ac9f017639ddb3873',
    messagingSenderId: '823070757258',
    projectId: 'test1-cc8b6',
    authDomain: 'test1-cc8b6.firebaseapp.com',
    storageBucket: 'test1-cc8b6.appspot.com',
  );
}
